baseURL: https://penrose.whitman.edu/archives
languageCode: en-us
defaultContentLanguage: en
title: Whitman College and Northwest Archives
theme: Penrose-Archive
googleAnalytics: 
disqusShortname: 
enableGitInfo: true
summaryLength: 55

taxonomies:
  tag: tags

permalinks:
  pages: /:filename/

imaging:
  quality: 99

params:
  description: 
  homeMetaContent: Whitman College and Northwest Archives Website
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to Cloudflare Page.
  # For more date formats see https://gohugo.io/functions/format/
  MatomoSiteID: 5
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: false
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: false
  moveFooterToHeader: false
  customCss:
    - css/simple-tooltip.css
    - css/custom.css
  customJs:
    - js/custom.js
    - js/van11y-accessible-simple-tooltip-aria.min.js

menu:
  nav:
    - name: About the Archives
      url: /about/
      weight: 1
    - name: Explore our Collections
      url: /collection/
      weight: 2
    - name: Information for Researchers
      weight: 3
      url: /research-services/
    - name: Instruction and Tours
      weight: 4
      url: /instruction-and-tours/
    - name: Digital Projects
      weight: 5
      url: /digital-projects/
    - name: <--Back to Penrose Library
      weight: 6
      url: ../
      

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false

  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
